image: docker:19.03.6

variables:
    PROJECT_PATH: ./src/Wally.RomMaster
    # Registry
    CI_REGISTRY_USER: wally
    CI_REGISTRY_PASSWORD: wally666
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    # DOCKER_HOST: tcp://docker:2376
    # DOCKER_TLS_CERTDIR: "/certs"
    # See https://github.com/docker-library/docker/pull/166
    #DOCKER_TLS_CERTDIR: ""
    #DOCKER_TLS_VERIFY: 0
    DOCKER_HOST: tcp://docker:2375/
    # DOCKER_HOST: tcp://localhost:2375
    SHARED_PATH: ${CI_PROJECT_DIR}/shared

services:
    - docker:19.03.6-dind
#services:
#    - name: docker:19.03.1-dind
#      entrypoint: ["env", "-u", "DOCKER_HOST"]
#      command: ["dockerd-entrypoint.sh"]
 
stages:
    - build
    - test
    - release
    - deploy

before_script:
    - export

build:
    stage: build
    tags: 
        - docker
    before_script:
        - export
        - docker -v
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker info
    script:
        - docker build ./src --pull -f $PROJECT_PATH/Dockerfile -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
        
test:
    stage: test
    tags:
        - docker
    before_script:
        - export
        - docker -v
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker info
    script:
        - echo ${DOCKER_DRIVER}
        - echo ${DOCKER_TLS_CERTDIR}
        - mkdir -p ${SHARED_PATH}
        - echo ${SHARED_PATH}
        - touch ${SHARED_PATH}/test_file
        - ls -al ${SHARED_PATH}
        - docker build ./src --pull --target test -f $PROJECT_PATH/Dockerfile -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_PIPELINE_ID}_test
        - docker run
            --rm
            --volume ${SHARED_PATH}:/mnt/artifacts:rw
            $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_PIPELINE_ID}_test
        - ls -al ${SHARED_PATH}
    artifacts:
        when: always
        expire_in: 30 days
        paths:
            - ${SHARED_PATH}/**/*
        reports:
            junit: 
                - ${SHARED_PATH}/*-test-result.xml        
    after_script:
        - docker logout $CI_REGISTRY
        
pages:
    stage: release
    dependencies:
        - build
    script:
        - mv ${CI_PROJECT_DIR}/artifacts/coverage/reports/ public/
    artifacts:
        when: always
        expire_in: 30 days
        paths:
            - public

release:
    stage: release
    tags: 
        - docker
    only:
        - master
    before_script:
        - docker -v
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker info
    script:
        - docker pull $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
        - docker tag $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
        - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
    after_script:
        - docker logout $CI_REGISTRY
        
deploy:
    stage: deploy
    tags:
        - ssh
    only:
        - master
    when: manual
    variables:
        GIT_STRATEGY: none
        GIT_CHECKOUT: "false"
        DOCKER: "/share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker"
    script:
        - $DOCKER login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - $DOCKER stop ${CI_PROJECT_PATH_SLUG} || true && $DOCKER rm ${CI_PROJECT_PATH_SLUG} || true
        - $DOCKER run
            --detach
            --name ${CI_PROJECT_PATH_SLUG}
            --network ${DOCKER_NETWORK}
            --volume "/share/Container/Wally.DevOps/auth/webserver.pfx:/certs/webserver.pfx:ro"
            --env "ASPNETCORE_ENVIRONMENT=Development"
            --env "ASPNETCORE_HTTPS_PORT=443"
            --env "ASPNETCORE_URLS=http://+:80;https://+:443"
            --env "ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/webserver.pfx"
            --env "ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASS}"
            --label "traefik.enable=true"
            --label "traefik.http.routers.${CI_PROJECT_PATH_SLUG}.entrypoints=http"
            --label "traefik.http.routers.${CI_PROJECT_PATH_SLUG}.rule=Host(\`${CI_PROJECT_PATH_SLUG}.${DOMAIN}\`)"
            --label "traefik.http.services.${CI_PROJECT_PATH_SLUG}.loadbalancer.server.port=80"
            --label "_traefik.http.routers.${CI_PROJECT_PATH_SLUG}-secure.entrypoints=https"
            --label "_traefik.http.routers.${CI_PROJECT_PATH_SLUG}-secure.rule=Host(\`${CI_PROJECT_PATH_SLUG}.${DOMAIN}\`)"
            --label "_traefik.http.routers.${CI_PROJECT_PATH_SLUG}-secure.tls=true"
            --label "_traefik.http.services.${CI_PROJECT_PATH_SLUG}-secure.loadbalancer.server.port=443"
            $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_PIPELINE_ID
        - $DOCKER logout $CI_REGISTRY
