default:
    tags: 
        - docker

variables:
    CI_DEBUG_TRACE: "false"
    CI_REGISTRY_USER: ${REGISTRY_USER}
    CI_REGISTRY_PASSWORD: ${REGISTRY_PASSWORD}
    SHARED_PATH: ${CI_PROJECT_DIR}/shared
    #
    API_PROJECT_NAME: "Wally.RomMaster"

stages:
    - build
    - test
    - publish
    - deploy

build:api:
    extends:
        - .build
        - .build:docker
    variables:
        PROJECT_NAME: ${API_PROJECT_NAME}

test:api:
    extends:
        - .test
        - .test:backend:docker
    variables:
        PROJECT_NAME: ${API_PROJECT_NAME}

publish:docker:api:
    extends:
        - .publish:docker
    variables:
        PROJECT_NAME: ${API_PROJECT_NAME}

deploy:container-station:
    extends:
        - .deploy:container-station

include:
    - local: .gitlab/ci/docker.gitlab-ci.yml
    - local: .gitlab/ci/build.gitlab-ci.yml
    - local: .gitlab/ci/test.gitlab-ci.yml
    - local: .gitlab/ci/publish.gitlab-ci.yml
    - local: .gitlab/ci/deploy.gitlab-ci.yml
