default:
    tags: 
        - docker

variables:
    CI_DEBUG_TRACE: "false"
    CI_REGISTRY_USER: ${REGISTRY_USER}
    CI_REGISTRY_PASSWORD: ${REGISTRY_PASSWORD}
    SHARED_PATH: ${CI_PROJECT_DIR}/shared
    #
    API_PROJECT_NAME: "Wally.RomMaster"

stages:
    - build
    - test
    - publish
    - deploy

build:api:
    extends:
        - .build:docker
    variables:
        PROJECT_NAME: ${API_PROJECT_NAME}

test:api:
    extends:
        - .test:docker:backend
    variables:
        PROJECT_NAME: ${API_PROJECT_NAME}

publish:api:
    extends:
        - .publish:docker:backend
    variables:
        PROJECT_NAME: ${API_PROJECT_NAME}

deploy:container-station:
    extends:
        - .deploy:container-station

include:
    - project: 'wally/wally.common.pipelines'
      ref: master
      file: 
        - /src/docker.gitlab-ci.yml
        - /src/build.gitlab-ci.yml
        - /src/build-docker.gitlab-ci.yml
        - /src/test.gitlab-ci.yml
        - /src/test-docker.gitlab-ci.yml
        - /src/publish.gitlab-ci.yml
        - /src/publish-docker.gitlab-ci.yml
        - /src/deploy.gitlab-ci.yml
        - /src/deploy-azure.gitlab-ci.yml
        - /src/deploy-container-station.gitlab-ci.yml
