variables:
  STACK: rommaster
  SLN_SOLUTION_NAME: "Wally.RomMaster"
  API_PROJECT_NAME: "Wally.RomMaster"
  #
  VERSION: "0.1.${CI_PIPELINE_ID}"
  #CI_DEBUG_TRACE: "true"

stages:
  - build
  - test
  - publish
  - deploy

.dotnet:
  # https://hub.docker.com/_/microsoft-dotnet-sdk
  image: mcr.microsoft.com/dotnet/sdk:5.0.402-alpine3.14-amd64

build:sln:
  extends:
    - .build:dotnet
  variables:
    SOLUTION_NAME: ${SLN_SOLUTION_NAME}

test:sln:
  extends:
    - .test:dotnet
  needs:
    - build:sln
  allow_failure: true
  variables:
    SOLUTION_NAME: ${SLN_SOLUTION_NAME}

publish:api:
  extends:
    - .publish:dotnet
  needs:
    - test:sln
  variables:
    PROJECT_NAME: ${API_PROJECT_NAME}

publish:docker:api:
  extends:
    - .publish:docker
  needs:
    - publish:api
  variables:
    PROJECT_NAME: ${API_PROJECT_NAME}

deploy:container-station:
  extends:
    - .deploy:container-station
  needs:
    - publish:docker:api
  variables:
    ENV: PROD

include:
  - project: wally/wally.common.pipelines
    ref: master
    file:
      - /src/gitlab-ci.yml