version: '3.9'

services:
    api:
        # http://localhost:5000
        # http://localhost:5000/healthchecks
        # http://localhost:5000/healthchecks-UI
        # http://localhost:5000/healthchecks-api
        # http://localhost:5000/healthchecks-api/ui-settings
        image: wally.rommaster.apigateway.webapi
        container_name: api
        restart: "no"
        networks:
            - default
        ports:
            - "5000:80"
        build:
            context: ./Wally.RomMaster.ApiGateway/Wally.RomMaster.ApiGateway.WebApi
            dockerfile: Dockerfile.development
        environment:
            TZ: ${TZ}
            PROJECT_NAME: Wally.RomMaster.ApiGateway.WebApi
            ASPNETCORE_URLS: http://+:80
            ASPNETCORE_ENVIRONMENT: Development
            DOTNET_DASHBOARD_OTLP_ENDPOINT_URL: http://aspire:18889
            OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire:18889
        volumes:
            - ./Wally.RomMaster.ApiGateway/Wally.RomMaster.ApiGateway.WebApi/bin/Debug/net8.0:/app:ro

    file_api:
        # http://localhost:5000/FileService-api/healthchecks
        container_name: file_api
        image: wally.rommaster.fileservice.webapi
        restart: "no"
        networks:
            - default
        build:
            context: ./Wally.RomMaster.FileService/Wally.RomMaster.FileService.WebApi
            dockerfile: Dockerfile.development
        entrypoint: dotnet Wally.RomMaster.FileService.WebApi.dll
        environment:
            TZ: ${TZ}
            PROJECT_NAME: Wally.RomMaster.FileService.WebApi
            ASPNETCORE_URLS: http://+:80
            ASPNETCORE_ENVIRONMENT: Development
            DOTNET_DASHBOARD_OTLP_ENDPOINT_URL: http://aspire:18889
            OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire:18889
        volumes:
            - ./Wally.RomMaster.FileService/Wally.RomMaster.FileService.WebApi/bin/Debug/net8.0:/app:ro
            - RomMaster:/RomMaster:ro
            - Books:/Books:ro
    
    hash_api:
        # http://localhost:5000/HashService-api/healthchecks
        container_name: hash_api
        image: wally.rommaster.hashservice.webapi
        restart: "no"
        networks:
            - default
        build:
            context: ./Wally.RomMaster.HashService/Wally.RomMaster.HashService.WebApi
            dockerfile: Dockerfile.development
        entrypoint: dotnet Wally.RomMaster.HashService.WebApi.dll
        environment:
            TZ: ${TZ}
            PROJECT_NAME: Wally.RomMaster.HashService.WebApi
            ASPNETCORE_URLS: http://+:80
            ASPNETCORE_ENVIRONMENT: Development
            DOTNET_DASHBOARD_OTLP_ENDPOINT_URL: http://aspire:18889
            OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire:18889
        volumes:
            - ./Wally.RomMaster.HashService/Wally.RomMaster.HashService.WebApi/bin/Debug/net8.0:/app:ro
            - RomMaster:/RomMaster:ro
            - Books:/Books:ro

    aspire:
        # http://localhost:18888
        # http://localhost:18889
        image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
        container_name: aspire
        restart: "no"
        networks:
            - default
        ports:
            - "18888:18888"
            - "18889:18889"
        environment:
            TZ: ${TZ}
            DASHBOARD__FRONTEND__BROWSERTOKEN: ${DASHBOARD__OTLP__PRIMARYAPIKEY} # Dashboard:Frontend:BrowserToken
            # DASHBOARD__OTLP__AUTHMODE: ApiKey
            # DASHBOARD__OTLP__PRIMARYAPIKEY: ${DASHBOARD__OTLP__PRIMARYAPIKEY}

volumes:
    RomMaster:
        name: RomMaster
        driver_opts:
            type: cifs
            o: username=${CIFS_USER},password=${CIFS_PASSWORD},vers=3.0
            device: ${VOLUME_Arcade}
    Books:
        name: Books
        driver_opts:
            type: cifs
            o: username=${CIFS_USER},password=${CIFS_PASSWORD},vers=3.0
            device: ${VOLUME_Books}

networks:
    default:
        external: false
        name: "Wally.RomMaster"
