// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wally.RomMaster.Database;

namespace Wally.RomMaster.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190427152905_FileCrcSizeIndex")]
    partial class FileCrcSizeIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview4.19216.3");

            modelBuilder.Entity("Wally.RomMaster.Domain.Models.Dat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Category");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int?>("FileId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Version")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("Dat");
                });

            modelBuilder.Entity("Wally.RomMaster.Domain.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Crc");

                    b.Property<string>("Md5");

                    b.Property<string>("Path")
                        .IsRequired();

                    b.Property<string>("Sha1");

                    b.Property<long>("Size");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("Crc", "Size")
                        .IsUnique();

                    b.ToTable("File");
                });

            modelBuilder.Entity("Wally.RomMaster.Domain.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DatId");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Year");

                    b.HasKey("Id");

                    b.HasIndex("DatId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Wally.RomMaster.Domain.Models.Rom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Crc");

                    b.Property<int?>("GameId");

                    b.Property<string>("Md5");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Sha1");

                    b.Property<long>("Size");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Rom");
                });

            modelBuilder.Entity("Wally.RomMaster.Domain.Models.Dat", b =>
                {
                    b.HasOne("Wally.RomMaster.Domain.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId");
                });

            modelBuilder.Entity("Wally.RomMaster.Domain.Models.Game", b =>
                {
                    b.HasOne("Wally.RomMaster.Domain.Models.Dat", null)
                        .WithMany("Games")
                        .HasForeignKey("DatId");
                });

            modelBuilder.Entity("Wally.RomMaster.Domain.Models.Rom", b =>
                {
                    b.HasOne("Wally.RomMaster.Domain.Models.Game", null)
                        .WithMany("Roms")
                        .HasForeignKey("GameId");
                });
#pragma warning restore 612, 618
        }
    }
}
