.build:
    stage: build
    variables:
        GIT_SUBMODULE_STRATEGY: recursive

.build:docker:
    extends:
        - .docker
    script:
        - docker
            --log-level debug
            build ./src
            --pull
            -f ./src/${PROJECT_NAME}/Dockerfile
            -t ${DOCKER_IMAGE_TAGGED}
            --build-arg PROJECT_NAME=${PROJECT_NAME}
        - docker push ${DOCKER_IMAGE_TAGGED}
